# Generated by Django 5.2.16 on 2026-07-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_audio/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="duration_seconds",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("audio", "Audio")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
