# Generated by Django 5.2.16 on 2026-07-22 20:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_message_voice_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="conversation",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="message",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
