# Generated by Django 5.2.16 on 2026-07-10 11:27

import secrets

from django.db import migrations, models


def populate_visitor_ids(apps, schema_editor):
    Contact = apps.get_model("contacts", "Contact")
    for contact in Contact.objects.filter(visitor_id=""):
        for _ in range(20):
            candidate = secrets.token_hex(4).upper()
            if not Contact.objects.filter(
                website_id=contact.website_id, visitor_id=candidate
            ).exists():
                contact.visitor_id = candidate
                contact.save(update_fields=["visitor_id"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("websites", "0002_website_activated_at_website_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("website", "session_id")},
        ),
        migrations.AddField(
            model_name="contact",
            name="visitor_id",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=16
            ),
        ),
        migrations.RunPython(populate_visitor_ids, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("website", "session_id"), ("website", "visitor_id")},
        ),
    ]
