# Generated by Django 5.2.16 on 2026-07-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_unique_together_contact_visitor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="telegram_link_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="telegram_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="telegram_user_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="telegram_username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
