# Generated by Django 5.2.16 on 2026-07-22 20:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_telegram_linking"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
