# Generated by Django 5.2.16 on 2026-07-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="metadata",
        ),
    ]
