# Generated by Django 5.2.16 on 2026-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="When active, the chat widget accepts visitor messages.",
            ),
        ),
    ]
