# Generated by Django 5.2.16 on 2026-07-22 20:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0002_website_activated_at_website_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="websiteagent",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
